source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CarlosSample', :exclusive => true do
end

target 'CarlosTests', :exclusive => true do
  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
