# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

fastlane_version "1.68.0"

desc "Runs all the tests"
lane :test do
  clear_derived_data
  scan(scheme: 'Carlos')
end
